---
title: "Downstream_analysis"
author: "Ville Lehtonen"
date: "9/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Set working dir to the source file location
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```
# Trajectory inference
SCORPIUS (https://github.com/rcannood/SCORPIUS) will be used for performing the trajectory inference as it is designed for inferring linear developmental trajectories from scRNA-seq data

## 1. Load packages
```{r}
library(SCORPIUS)
library(scater)
library(scran)
library(SingleCellExperiment)
library(dplyr)
```

### Load saved sce objects
```{r}
denoised.sce.deMicheli <- readRDS("./../saved/denoised_sce_deMicheli")
denoised.sce.dellOrso <- readRDS("./../saved/denoised_sce_dellOrso")
```


## 2. Trajectory inference
### 12.4 De Micheli et al. (2020) reference data
```{r}
# Create expression and sample objects
expression.deMicheli <- as.matrix(t(logcounts(denoised.sce.deMicheli)))
group_name.deMicheli <- as.factor(denoised.sce.deMicheli$injury)

# Trajectory inference
space.deMicheli <- reduce_dimensionality(expression.deMicheli, dist = "spearman")
traj.deMicheli <- infer_trajectory(space.deMicheli)

draw_trajectory_plot(space = space.deMicheli, 
                     progression_group = group_name.deMicheli,
                     path = traj.deMicheli$path,
                     contour = TRUE)

# Identify candidate marker genes
gimp.deMicheli <- gene_importances(x = expression.deMicheli,
                                   time = traj.deMicheli$time,
                                   num_permutations = 0,
                                   num_threads = 8)

gene_sel.deMicheli <- gimp.deMicheli[1:50,]
expr_sel.deMicheli <- expression.deMicheli[, gene_sel.deMicheli$gene]

# Visualize expression of selected genes
draw_trajectory_heatmap(expr_sel.deMicheli, 
                        time = traj.deMicheli$time,
                        progression_group = group_name.deMicheli)

# Group genes to modules
modules.deMicheli <- extract_modules(scale_quantile(expr_sel.deMicheli),
                                     time = traj.deMicheli$time,
                                     verbose = FALSE)

draw_trajectory_heatmap(expr_sel.deMicheli, 
                        time = traj.deMicheli$time,
                        progression_group = group_name.deMicheli,
                        modules = modules.deMicheli)
```


### 12.5 Dell'Orso et al. (2019) reference data
```{r}
# Merge replicate samples
hom1 <- denoised.sce.dellOrso$sample == "homeostatic_MuSCs_rep1"
hom2 <- denoised.sce.dellOrso$sample == "homeostatic_MuSCs_rep2"
inj1 <- denoised.sce.dellOrso$sample == "inj_60h_MuSCs_rep1"
inj2 <- denoised.sce.dellOrso$sample == "inj_60h_MuSCs_rep2"
pmb <- denoised.sce.dellOrso$sample == "Primary_MB"
  
denoised.sce.dellOrso$cell_type[hom1] <- "homeostatic_MuSCs" 
denoised.sce.dellOrso$cell_type[hom2] <- "homeostatic_MuSCs" 
denoised.sce.dellOrso$cell_type[inj1] <- "inj_60h_MuSCs" 
denoised.sce.dellOrso$cell_type[inj2] <- "inj_60h_MuSCs" 
denoised.sce.dellOrso$cell_type[pmb] <- "Primary_MB"

# Create expression and sample objects
expression.dellOrso <- as.matrix(t(logcounts(denoised.sce.dellOrso)))
group_name.dellOrso <- as.factor(denoised.sce.dellOrso$cell_type)

# Trajectory inference
space.dellOrso <- reduce_dimensionality(expression.dellOrso, dist = "spearman")
traj.dellOrso <- infer_trajectory(space.dellOrso)

draw_trajectory_plot(space = space.dellOrso, 
                     progression_group = group_name.dellOrso,
                     path = traj.dellOrso$path,
                     contour = TRUE)

# Identify candidate marker genes
gimp.dellOrso <- gene_importances(x = expression.dellOrso,
                                   time = traj.dellOrso$time,
                                   num_permutations = 0,
                                   num_threads = 8)

gene_sel.dellOrso <- gimp.dellOrso[1:50,]
expr_sel.dellOrso <- expression.dellOrso[, gene_sel.dellOrso$gene]

# Visualize expression of selected genes
draw_trajectory_heatmap(expr_sel.dellOrso, 
                        time = traj.dellOrso$time,
                        progression_group = group_name.dellOrso)

# Group genes to modules
modules.dellOrso <- extract_modules(scale_quantile(expr_sel.dellOrso),
                                     time = traj.dellOrso$time,
                                     verbose = FALSE)

draw_trajectory_heatmap(expr_sel.dellOrso, 
                        time = traj.dellOrso$time,
                        progression_group = group_name.dellOrso,
                        modules = modules.dellOrso)
```


